[view]
interface = 'raw'

[timers]
timer = 10
minor_break = 10
major_break = 15
intervals = 2
postpone_limit = 3
postpone_timer = 10

[notifications]
enable_bell = true
volume = 0.5
show_notification = true
